import {seedStore,channels} from '../mock/data';
import type {Action,Role,Store,Engine,Config,Sample,Fault,MissionProfile,Simulation} from '../types';
const KEY='aerotwin-prototype-v1';
let state:Store=seedStore();try{const saved=JSON.parse(localStorage.getItem(KEY)||'null');if(saved?.version===1)state=saved;}catch{}
let listeners=new Set<()=>void>();let failure=false;
const permission:Record<Action,Role[]>={ack:['Operator','Engineer','Maintenance','Admin'],contain:['Operator','Engineer','Admin'],maintenance:['Maintenance','Engineer','Admin'],simulate:['Planner','Engineer','Admin'],inject:['Engineer','Admin'],admin:['Admin'],config:['Engineer','Admin'],model:['Engineer','Admin']};
export const can=(role:Role|null,action:Action)=>!!role&&permission[action].includes(role);
export function audit(s:Store,action:string,target:string,result='Success'){s.audit.unshift({id:'EV-'+Date.now()+'-'+s.audit.length,time:new Date().toISOString(),actor:s.session||'Engineer',action,target,result});s.audit=s.audit.slice(0,200);}
function publish(){try{localStorage.setItem(KEY,JSON.stringify(state));}catch{}listeners.forEach(f=>f());}
export const api={
 getSnapshot:()=>state,
 subscribe:(f:()=>void)=>{listeners.add(f);return()=>{listeners.delete(f);}},
 failNext:()=>{failure=true;},
 async read(){await new Promise(r=>setTimeout(r,350));if(failure){failure=false;throw Error('Simulated connection error. No local data was changed. Retry when ready.');}return state;},
 async mutate(action:Action|null,label:string,target:string,fn:(s:Store)=>void){await new Promise(r=>setTimeout(r,380));if(failure){failure=false;throw Error('Simulated service failure. Your changes were not saved. Please retry.');}if(action&&!can(state.session,action)){state=structuredClone(state);audit(state,label,target,'Denied by demo role');publish();throw Error('Your demo role is not permitted to perform this action.');}const next=structuredClone(state);fn(next);audit(next,label,target);state=next;publish();},
 reset(){state=seedStore();publish();},
};
export function aggregate(engine:Engine,config:Config){const weighted=engine.hi.reduce((a,n,i)=>a+n*config.weights[i],0)/config.weights.reduce((a,b)=>a+b,0);return Math.round(.55*Math.min(...engine.hi)+.45*weighted);}
export function band(value:number,config?:Config){const [healthy,watch,warning]=config?.bands||[90,70,40];return value>=healthy?'Healthy':value>=watch?'Watch':value>=warning?'Warning':'Critical';}
export function random(seed:number,index:number){let n=(seed^Math.imul(index+1,2654435761))>>>0;n=Math.imul(n^(n>>>16),2246822507);return((n^(n>>>13))>>>0)/4294967295;}
export function activeChannels(config:Config){return channels.filter(c=>!(/^(cht|egt)_/.test(c.key)&&Number(c.key.split('_')[1])>config.cylinders)&&!(c.key==='coolant_temp'&&config.cooling==='Air'));}
export function telemetry(tick:number,engine:Engine,config:Config,fault:Fault='Normal',virtual=false):Sample[]{return activeChannels(config).map((c,i)=>{const wave=Math.sin(tick/15+i)*.002*c.base;let measured=c.base+wave+(random(42+engine.id.length,tick+i)-.5)*.001*c.base;let predicted=c.base+wave*.6;if(engine.id==='AT-024'&&c.key==='oil_press')predicted=54.8;if(engine.id==='AT-024'&&c.key==='oil_temp')predicted=93.9;if(engine.id==='AT-024'&&c.key==='cht_2')predicted=180;if(engine.id!=='AT-024'){measured=predicted+(random(17,tick+i)-.5)*.002*c.base;}if(fault==='Sensor drift/failure'&&c.key==='cht_2')measured=248;if((fault==='Cooling degradation'||fault==='Overheating trend')&&c.key.startsWith('cht'))measured+=28;if(fault==='Lubrication issue'&&c.key==='oil_press')measured-=12;if(fault==='Lubrication issue'&&c.key==='oil_temp')measured+=16;if((fault==='Misfire'||fault==='Injector abnormality')&&c.key==='egt_3')measured-=90;if(fault==='Abnormal vibration'&&c.key.startsWith('vib'))measured*=3;if(fault==='Combustion instability'&&c.key.startsWith('egt'))measured+=Math.sin(tick)*55;const reconstructed=virtual&&fault==='Sensor drift/failure'&&c.key==='cht_2';if(reconstructed)measured=predicted;return{key:c.key,measured,predicted,residual:measured-predicted,time:tick,reconstructed};});}
export function simulate(profile:MissionProfile,engine:Engine,config:Config):Simulation{
 const faultFactor=profile.fault==='Normal'?0:Math.min(1,Math.max(0,(profile.duration-profile.onset)/Math.max(.1,profile.ramp)));
 const peak=185+(profile.ambient-24)*.65+(profile.altitude-6000)*.002+(profile.throttle-60)*.5+(101.3-profile.pressure)*.015+(profile.load-24)*.06+(profile.altitudeSchedule==='Stepped climb'?3:0)+(profile.throttleProfile.includes('steps')?5:0)+faultFactor*14;
 const flow=5.9125*(profile.throttle/68)*(1+(profile.load-24)*.0015)*(profile.throttleProfile==='Economy cruise'?.94:1);
 const fuel=flow*profile.duration;const margin=config.chtLimit-peak;const endHi=Math.max(0,aggregate(engine,config)-profile.duration*.3-Math.max(0,15-margin)*.2-faultFactor*12);
 const risk=margin<5||fuel>profile.fuel?'HIGH':margin<15||fuel>profile.fuel*.95?'ELEVATED':'LOW';const driver=margin<15?'Climb segment thermal margin below 15 °C':fuel>profile.fuel*.95?'Fuel reserve below 5%':'No configured synthetic margin exceeded';
 const series=Array.from({length:49},(_,i)=>{const t=i/48,noise=(random(profile.seed,i)-.5)*1.2,shape=.74+.26*Math.sin(Math.PI*Math.min(1,t*3));return{time:t*profile.duration,rpm:profile.throttle*70+noise*4,cht:peak-15*(1-shape)+noise,egt:675+(profile.throttle-60)*2+12*shape+noise,oilTemp:89+(profile.ambient-24)*.35+8*t+noise*.3,oilPress:54-4*t-faultFactor*10*t,fuelFlow:flow*(.98+.04*shape),hi:aggregate(engine,config)+(endHi-aggregate(engine,config))*t};});
 const actualPeak=Math.max(...series.map(p=>p.cht));const actualMargin=config.chtLimit-actualPeak;const actualRisk=actualMargin<5||fuel>profile.fuel?'HIGH':actualMargin<15||fuel>profile.fuel*.95?'ELEVATED':'LOW';
 return{id:'RUN-'+Date.now(),engineId:engine.id,profile:{...profile},created:new Date().toISOString(),risk:actualRisk,driver:actualMargin<15?'Climb segment thermal margin below 15 °C':driver,fuel,peak:actualPeak,margin:actualMargin,endHi,rulUsed:[profile.duration*.8,profile.duration*1.1,profile.duration*1.5],stress:Math.max(0,actualPeak-180)*profile.duration/12,series};
}
export function trendSeries(key:string,window:string,engine:Engine,config:Config){const c=channels.find(c=>c.key===key)!;const length=24;return Array.from({length},(_,i)=>{const sample=telemetry(i*5,engine,config).find(s=>s.key===key)!;const factor=window==='7 d'?1.7:window==='30 d'?2.4:window==='Life'?3.2:1;const degradation=key==='oil_press'?(length-1-i)*.14*factor:key.startsWith('cht')?-(length-1-i)*.24*factor:0;return{label:window==='This mission'?`${(i*8/(length-1)).toFixed(1)} h`:window==='Life'?`${Math.round(engine.hours*i/(length-1))} h`:`${Math.round(i*(window==='7 d'?7:30)/(length-1))} d`,measured:sample.measured+degradation,predicted:sample.predicted};});}
