import React,{useEffect,useRef,useState} from 'react';
import {LuRotateCcw,LuMaximize2,LuMinus,LuPlus} from 'react-icons/lu';
import {Button} from './ui';
import {subsystems} from '../mock/data';
type V=[number,number,number];type Face={points:V[];color:string;system:string};
function box(x:number,y:number,z:number,w:number,h:number,d:number,color:string,system:string):Face[]{const p:V[]=[[-1,-1,-1],[1,-1,-1],[1,1,-1],[-1,1,-1],[-1,-1,1],[1,-1,1],[1,1,1],[-1,1,1]].map(([a,b,c])=>[x+a*w/2,y+b*h/2,z+c*d/2]);return [[0,1,2,3],[4,7,6,5],[0,4,5,1],[3,2,6,7],[0,3,7,4],[1,5,6,2]].map(indices=>({points:indices.map(i=>p[i]),color,system}));}
function cylinder(x:number,y:number,z:number,r:number,length:number,color:string,system:string):Face[]{const n=20;const faces:Face[]=[];const ring=(k:number):V[]=>Array.from({length:n},(_,i)=>[x+Math.cos(i/n*Math.PI*2)*r,y+Math.sin(i/n*Math.PI*2)*r,z+k*length/2]);const a=ring(-1),b=ring(1);faces.push({points:a,color,system},{points:b,color,system});for(let i=0;i<n;i++)faces.push({points:[a[i],a[(i+1)%n],b[(i+1)%n],b[i]],color,system});return faces;}
export function Engine3D({selected:selectedProp='Thermal',onSelect,cylinders=4,compact=false}:any){const [localSelected,setLocalSelected]=useState(selectedProp);const selected=onSelect?selectedProp:localSelected;const choose=(s:string)=>{setLocalSelected(s);onSelect?.(s)};const canvas=useRef<HTMLCanvasElement>(null);const [rotation,setRotation]=useState([-.46,.65]);const [zoom,setZoom]=useState(1);const [explode,setExplode]=useState(false);const drag=useRef<any>(null);const [size,setSize]=useState([600,330]);useEffect(()=>{const c=canvas.current;if(!c)return;const observer=new ResizeObserver(e=>setSize([e[0].contentRect.width,compact?280:370]));observer.observe(c);return()=>observer.disconnect()},[compact]);
useEffect(()=>{const c=canvas.current;if(!c)return;const ctx=c.getContext('2d');if(!ctx)return;const [w,h]=size;const dpr=Math.min(devicePixelRatio||1,2);c.width=w*dpr;c.height=h*dpr;ctx.scale(dpr,dpr);ctx.clearRect(0,0,w,h);const faces:Face[]=[];const add=(f:Face[])=>faces.push(...f);const gap=explode?24:0;
add(box(0,5,0,86,78,125,'#536f89','Mechanical'));add(box(0,60+gap,0,70,27,94,'#617a8b','Lubrication'));add(cylinder(0,2,86+gap,31,45,'#708898','Mechanical'));add(cylinder(0,2,119+gap,13,26,'#a8b9c6','Mechanical'));add(box(0,-58-gap,0,52,22,104,'#839bad','Fuel'));add(box(0,-82-gap,4,64,20,55,'#445f78','Fuel'));add(cylinder(0,-38, -84-gap,22,27,'#739084','Electrical'));
for(let i=0;i<cylinders;i++){const side=i%2===0?-1:1;const z=(Math.floor(i/2)-(Math.ceil(cylinders/2)-1)/2)*57;const x=side*(66+gap);add(box(x,-5,z,54,50,43,'#758da0','Combustion'));for(let f=0;f<7;f++)add(box(x+side*(f*3-10),-5,z,2,59,49,'#93a7b6','Thermal'));add(box(x+side*28,-7,z,14,49,42,'#527ca5','Thermal'));add(box(x+side*29,-38,z,11,16,9,'#d4bc83','Electrical'));add(box(x,33,z,13,28,14,'#9c8970','Fuel'));}
const project=(p:V)=>{const [pitch,yaw]=rotation;const x=p[0]*Math.cos(yaw)+p[2]*Math.sin(yaw),z=-p[0]*Math.sin(yaw)+p[2]*Math.cos(yaw);const y=p[1]*Math.cos(pitch)-z*Math.sin(pitch),depth=p[1]*Math.sin(pitch)+z*Math.cos(pitch);const s=Math.min(w/420,h/290)*zoom*(650/(650+depth));return{x:w/2+x*s,y:h/2+y*s,z:depth};};
ctx.strokeStyle='rgba(120,158,197,.10)';ctx.lineWidth=1;for(let n=-5;n<=5;n++){for(const direction of [0,1]){const a=project(direction===0?[n*45,110,-220]:[-220,110,n*45]);const b=project(direction===0?[n*45,110,220]:[220,110,n*45]);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();}}
const projected=faces.map(f=>({...f,points:f.points.map(project)})).sort((a,b)=>b.points.reduce((s,p)=>s+p.z,0)/b.points.length-a.points.reduce((s,p)=>s+p.z,0)/a.points.length);
projected.forEach(f=>{const a=f.points[0],b=f.points[1],c=f.points[2];const area=(b.x-a.x)*(c.y-a.y)-(b.y-a.y)*(c.x-a.x);ctx.beginPath();f.points.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.closePath();ctx.fillStyle=f.system===selected?(selected==='Thermal'?'#c69541':selected==='Lubrication'?'#579ea3':'#6098cc'):f.color;ctx.fill();ctx.fillStyle=`rgba(8,20,35,${area<0?.30:.07})`;ctx.fill();ctx.strokeStyle='rgba(10,22,38,.38)';ctx.lineWidth=.6;ctx.stroke();});
},[rotation,zoom,explode,selected,cylinders,size]);
return <div className={`engine3d ${compact?'compact':''}`}><div className="engine-caption"><span>SPATIAL TWIN / {cylinders} CYL</span><span className="engine-tag">{selected.toUpperCase()}</span></div><canvas ref={canvas} style={{height:compact?280:370}} aria-label="Interactive 3D schematic of a piston engine. Drag to orbit. Use arrow keys to rotate, plus or minus buttons to zoom. Select subsystems below." tabIndex={0} onPointerDown={e=>{drag.current=[e.clientX,e.clientY,...rotation];e.currentTarget.setPointerCapture(e.pointerId)}} onPointerMove={e=>{if(drag.current)setRotation([drag.current[2]+(e.clientY-drag.current[1])*.008,drag.current[3]+(e.clientX-drag.current[0])*.008])}} onPointerUp={()=>drag.current=null} onPointerCancel={()=>drag.current=null} onKeyDown={e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();setRotation(([x,y])=>[x+(e.key==='ArrowUp'?-.1:e.key==='ArrowDown'?.1:0),y+(e.key==='ArrowLeft'?-.1:e.key==='ArrowRight'?.1:0)]);}}}/><div className="engine-toolbar"><small>Drag to orbit · schematic, not CAD</small><div><Button aria-label="Zoom out" onClick={()=>setZoom(v=>Math.max(.6,v-.1))}><LuMinus/></Button><Button aria-label="Zoom in" onClick={()=>setZoom(v=>Math.min(1.5,v+.1))}><LuPlus/></Button><Button aria-label="Reset 3D view" onClick={()=>{setZoom(1);setRotation([-.46,.65]);setExplode(false)}}><LuRotateCcw/></Button><Button aria-pressed={explode} onClick={()=>setExplode(!explode)}><LuMaximize2/>{explode?'Assemble':'Explode'}</Button></div></div><div className="subsystem-chips">{subsystems.map(s=><button key={s} aria-pressed={s===selected} onClick={()=>choose(s)}>{s}</button>)}</div></div>}
