import {chromium} from 'playwright';
import fs from 'node:fs';
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH||(fs.existsSync('/usr/local/bin/chromium')?'/usr/local/bin/chromium':undefined),args:['--no-sandbox','--disable-dev-shm-usage']});
const page=await browser.newPage({viewport:{width:1440,height:1000},acceptDownloads:true});const errors=[];const checks=[];page.on('pageerror',e=>errors.push(e.message));const base='file://'+process.cwd()+'/AeroTwin.html';const wait=()=>page.waitForTimeout(500);
async function check(name,fn){try{await fn();checks.push({name,status:'pass'});console.log('PASS',name)}catch(e){checks.push({name,status:'fail',error:e.message});console.log('FAIL',name,e.message)}}
fs.mkdirSync('qa',{recursive:true});
async function route(r){await page.evaluate(r=>location.hash=r,r);await wait()}
try{
 await page.goto(base);await wait();
 await check('Demo sign-in and onboarding',async()=>{await page.getByRole('checkbox').check();await page.getByRole('button',{name:'Enter demo workspace'}).click();await page.getByRole('button',{name:'Explore workspace'}).click();await page.getByRole('heading',{name:'Engine overview',exact:true}).waitFor();});
 await wait();await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:'qa/overview-desktop.png',fullPage:true});
 for(const r of ['overview','twin','telemetry','alerts','diagnostics','maintenance','simulator','replay','reports','fleet','system','admin','settings','help'])await check('Route '+r,async()=>{await route(r);if(await page.getByText('AeroTwin could not render this view.').count())throw Error('Error boundary');if(!(await page.locator('main h1').count()))throw Error('No page heading');await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:'qa/'+r+'-desktop.png',fullPage:true});const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);if(overflow)throw Error('Horizontal overflow')});
 await check('Alert acknowledgment and persistence',async()=>{await route('alerts');await page.getByRole('button',{name:/CHT bank-1 thermal divergence/}).click();await page.getByRole('button',{name:'Acknowledge',exact:true}).click();await wait();if(!(await page.locator('dialog').getByText('Acknowledged',{exact:true}).count()))throw Error('Not acknowledged');await page.getByRole('button',{name:'Close dialog'}).click();await page.reload();await wait();if(!(await page.getByText('Acknowledged',{exact:true}).count()))throw Error('Acknowledgment not persisted')});
 await check('Telemetry search and empty-state recovery',async()=>{await route('telemetry');await page.getByLabel('Search channels').fill('impossible');if(!(await page.getByText('No matching records').count()))throw Error('No empty state');await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:'qa/telemetry-empty.png',fullPage:true});await page.getByRole('button',{name:'Clear filters'}).click();await page.getByLabel('Search channels').fill('oil');if(!(await page.getByRole('button',{name:/Oil pressure/}).count()))throw Error('Search missing')});
 await check('3D orbit, explode and subsystem controls',async()=>{await route('twin');const c=page.locator('canvas');await c.focus();await c.press('ArrowRight');await page.getByRole('button',{name:'Explode',exact:true}).click();await page.getByRole('button',{name:'Lubrication',exact:true}).click();await page.getByRole('button',{name:'Zoom in',exact:true}).click();await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:'qa/twin-exploded.png',fullPage:true});await page.getByRole('button',{name:'Reset 3D view'}).click()});
 await check('Mission simulation, parameter change and comparison',async()=>{await route('simulator');await page.getByRole('button',{name:'Run mission simulation',exact:true}).click();await page.getByText('ELEVATED · SIMULATED RISK').waitFor();await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:'qa/simulation-results.png',fullPage:true});await page.getByRole('button',{name:'Adjust & rerun'}).click();await page.getByLabel('Cruise altitude (ft)',{exact:true}).fill('6000');await page.getByRole('button',{name:'Run mission simulation',exact:true}).click();await page.getByText('LOW · SIMULATED RISK').waitFor();const opts=await page.getByLabel('Comparison run').locator('option').allTextContents();if(opts.length<2)throw Error('Missing saved run');await page.getByLabel('Comparison run').selectOption({index:1});await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:'qa/simulation-comparison.png',fullPage:true})});
 await check('Replay seek, event jump, speed and reanalysis',async()=>{await route('replay');await page.getByRole('button',{name:/03:12:40/}).click();await page.getByText('DIVERGENCE OBSERVED').waitFor();await page.getByLabel('Playback speed').selectOption('60');await page.getByRole('button',{name:'Play',exact:true}).click();await wait();await page.getByRole('button',{name:'Pause',exact:true}).click();await page.getByLabel('Compare newer-model reanalysis').check();await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:'qa/replay-active.png',fullPage:true})});
 await check('Maintenance schedule and annotated action',async()=>{await route('maintenance');await page.getByRole('button',{name:'Review & annotate'}).first().click();await page.getByLabel('Inspection date').fill('2026-09-12');await page.getByLabel('Engineer note (required)').fill('Inspection assigned to demo hangar team.');await page.getByRole('button',{name:'Schedule inspection'}).click();await wait();await page.getByText('Scheduled 2026-09-12').waitFor();await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:'qa/maintenance-scheduled.png',fullPage:true})});
 await check('Sensor fault injection and virtual estimate',async()=>{await route('diagnostics');await page.getByLabel('Scenario',{exact:true}).selectOption('Sensor drift/failure');await page.getByRole('button',{name:'Apply demo scenario'}).click();await wait();await page.getByRole('tab',{name:'Sensor integrity'}).click();await page.getByText('SENSOR FAULT SUSPECTED',{exact:true}).waitFor();await page.getByLabel('Substitute virtual CHT-2 estimate').check();await wait();await page.getByText('RECONSTRUCTED / active',{exact:true}).waitFor();await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:'qa/sensor-integrity.png',fullPage:true})});
 await check('Link loss freezes sample clock and recovery',async()=>{await route('system');await page.getByRole('button',{name:'Simulate link loss'}).click();await wait();await page.getByText('Telemetry stale — derived analytics degraded').waitFor();await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:'qa/system-stale.png',fullPage:true});await page.getByRole('button',{name:'Restore demo link'}).click();await wait();if(await page.getByText('Telemetry stale — derived analytics degraded').count())throw Error('Stale banner persisted')});
 await check('CSV report download and print preview',async()=>{await route('reports');const dl=page.waitForEvent('download');await page.getByRole('button',{name:'Export CSV S-124'}).click();const file=await dl;await file.saveAs('qa/'+file.suggestedFilename());const text=fs.readFileSync('qa/'+file.suggestedFilename(),'utf8');if(!text.includes('p90')||!text.includes('SYNTHETIC'))throw Error('Missing provenance');await page.getByRole('button',{name:'Preview',exact:true}).first().click();await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:'qa/report-dialog.png',fullPage:true});await page.pdf({path:'qa/sample-mission-report.pdf',format:'A4',printBackground:true});await page.getByRole('button',{name:'Close dialog'}).click()});
 await check('Units preference persists',async()=>{await route('settings');await page.getByLabel('Temperature units').selectOption('F');await page.getByLabel('Oil pressure units').selectOption('bar');await page.getByRole('button',{name:'Save preferences'}).click();await wait();await route('telemetry');if(!(await page.getByText(/°F/).count()))throw Error('Units did not update');await route('settings');await page.getByLabel('Temperature units').selectOption('C');await page.getByLabel('Oil pressure units').selectOption('PSI');await page.getByRole('button',{name:'Save preferences'}).click();await wait()});
 await check('One-shot service error',async()=>{await route('help');await page.getByRole('button',{name:'Fail next mock request'}).click();await route('settings');await page.getByRole('button',{name:'Save preferences'}).click();await wait();await page.getByText(/Simulated service failure/).waitFor();await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:'qa/service-error.png',fullPage:true});await page.getByRole('button',{name:'Save preferences'}).click();await wait()});
 for(const width of [820,390])await check('Responsive routes '+width,async()=>{await page.setViewportSize({width,height:900});for(const r of ['overview','twin','telemetry','alerts','diagnostics','maintenance','simulator','replay','reports','fleet','system','admin','settings','help']){await route(r);await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:`qa/${r}-${width}.png`,fullPage:true});if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error(r+' horizontal overflow')}});
 await check('Mobile drawer navigation',async()=>{await page.getByRole('button',{name:'Open navigation menu'}).click();await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:'qa/mobile-menu.png',fullPage:true});await page.locator('nav').getByRole('link',{name:'Digital twin',exact:true}).click();await wait();if(await page.locator('.sidebar.open').count())throw Error('Drawer remained open')});
 await check('Operator restrictions',async()=>{await route('settings');await page.getByRole('button',{name:'Sign out / change role'}).click();await wait();await page.getByLabel('Choose a demo role').selectOption('Operator');await page.getByRole('checkbox').check();await page.getByRole('button',{name:'Enter demo workspace'}).click();await page.getByRole('button',{name:'Explore workspace'}).click();await wait();await route('simulator');if(!(await page.getByRole('button',{name:'Run mission simulation'}).isDisabled()))throw Error('Operator can simulate');await route('admin');await page.getByRole('heading',{name:'Restricted workspace'}).waitFor();await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:'qa/operator-restricted.png',fullPage:true})});
 await check('404 recovery',async()=>{await route('unknown-page');await page.getByRole('heading',{name:'404'}).waitFor();await page.getByRole('button',{name:'Back to overview'}).click();await wait()});
}finally{fs.writeFileSync('qa/browser-results.json',JSON.stringify({checks,errors},null,2));console.log(JSON.stringify({checks,errors},null,2));await browser.close();process.exit(checks.some(c=>c.status==='fail')||errors.length?1:0)}
